config/routes.rb
Rails.application.routes.draw do
    get 'passwords/home'

    get 'auth/:provider/callback', to: 'sessions#create'
    get 'auth/failure', to: redirect('/')
    get 'signout', to: 'sessions#destroy', as: 'signout'

    resources :passwords
    resource :customers
    root to: "passwords#home"
end

app/models/customer.rb
class Customer < ActiveRecord::Base
end

app/models/password.rb
class Password < ActiveRecord::Base
  belongs_to :customers
end

app/models/user.rb
class User < ActiveRecord::Base
def self.from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.provider = auth.provider 
    user.uid      = auth.uid
    user.name     = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
    user.save
  end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
    def after_sign_in_path_for(user)
    "password#new"
end
  helper_method :current_user
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
        params.require(:customer).permit(:FirstName, :LastName, :Email, :Telephone)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  before_action :set_password, only: [:show, :edit, :update, :destroy]

  # GET /passwords
  # GET /passwords.json
  def index
    @passwords = Password.all
  end

  # GET /passwords/1
  # GET /passwords/1.json
  def show
  end

  # GET /passwords/new
  def new
    @password = Password.new
  end

  # GET /passwords/1/edit
  def edit
  end

  # POST /passwords
  # POST /passwords.json
  def create
    @password = Password.new(password_params)

    respond_to do |format|
      if @password.save
        format.html { redirect_to @password, notice: 'Password was successfully created.' }
        format.json { render :show, status: :created, location: @password }
      else
        format.html { render :new }
        format.json { render json: @password.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /passwords/1
  # PATCH/PUT /passwords/1.json
  def update
    respond_to do |format|
      if @password.update(password_params)
        format.html { redirect_to @password, notice: 'Password was successfully updated.' }
        format.json { render :show, status: :ok, location: @password }
      else
        format.html { render :edit }
        format.json { render json: @password.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /passwords/1
  # DELETE /passwords/1.json
  def destroy
    @password.destroy
    respond_to do |format|
      format.html { redirect_to passwords_url, notice: 'Password was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_password
      @password = Password.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def password_params
      params.require(:password).permit(:Title, :Group, :UserName, :Password)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :FirstName %><br>
      <%= f.text_field :FirstName %>
  </div>
  <div class="field">
    <%= f.label :LastName %><br>
      <%= f.text_field :LastName %>
  </div>
  <div class="field">
    <%= f.label :Email %><br>
      <%= f.text_field :Email %>
  </div>
  <div class="field">
      <%= f.label :Password %><br>
      <%= f.password_field :Telephone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer , :class=>'button'%> |
<%= link_to 'Back', customers_path , :class=>'button' %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>
<style>
table {
    border-collapse: collapse;
    width: 100%;
}

th, td {
    text-align: left;
    padding: 8px;
}

tr:nth-child(even){background-color: #f2f2f2}

th {
    background-color: #f44336;
    color: white;
}  
.button {
    background-color: #f44336; /* Green */
    border: none;
    color: white;
    padding: 10px 20px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
} 
    a:visited { 
    color: white;
}
</style>
<h1>Customers List</h1>

<table>
  <thead>
    <tr>
      <th>Customer ID</th>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.id %></td>
        <td><%= customer.FirstName %></td>
        <td><%= customer.LastName %></td>
        <td><%= customer.Email %></td>  
        <td><%= '********' %></td>
          <td><%= link_to 'Show', customer, :class=>'button' %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer), :class=>'button' %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' }, :class=>'button' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path, :class=>'button' %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form' %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @customer.FirstName %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @customer.LastName %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.Email %>
</p>
<p>
  <strong>Telephone:</strong>
  <%= @customer.Telephone %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer), :class=>'button' %> |
<%= link_to 'Back', customers_path, :class=>'button' %>

app/views/home/show.html.erb
<h1>Home#show</h1>
<p>Find me in app/views/home/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <style>
    input[type=text], select {
    width: 50%;
    padding: 5px 10px;
    display: inline-block;
    border: solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
}
   input[type=password] {
    width: 50%;
    padding: 5px 10px;
    display: inline-block;
    border: solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
}

input[type=submit] {
    width: 50%;
    background-color: #f44336;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    border-radius: 4px;
    cursor: pointer;
}

input[type=submit]:hover {
    background-color: #4CAF50;
}

div {
    border-radius: 5px;
    background-color: white;
    padding: 20px;
}
        h1{
        color: #f44336;
        }
.button {
    background-color: #f44336; /* Green */
    border: none;
    color: white;
    padding: 10px 20px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
} 
    a:visited { 
    color: white;
}
 .topcorner{
   position:absolute;
   top:0;
   right:0;
  } 
.left{
        padding-right:1100px;
}
    </style>
    
<head>
  <title>PCracking</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
    <div id="user_nav" class="topcorner">
  <% if current_user %>
    Signed in as <strong><%= current_user.name %></strong>!
    <%= link_to "Sign out", signout_path, id: "sign_out", :class=>'button'   %>
    <%= link_to 'New Password', new_password_path, :class=>'button' %>
  <% else %>
    <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in", :class=>'button'  %>
  <% end %>
        </div>
</head>
<body>
<a href="passwords/home"><h1 class="left">PCracking</h1></a>
    <h6 class="left">A Password Manager Website!</h6>
    <hr >
<%= yield %>

    

</body>
</html>